name: atctest
favicon: null
layout_spectrum: 0.5760666762944311
typography_spectrum: 0.6042462766636163
title: ATC Test site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.30635361932218075
  lightness: 0.1149602085351944
  saturation: 0.7443312290124595
  rhythmicContrast: 0.059577831299975514
purpose: []
